---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: icos-downloader-cronjob
  namespace: field-observatory
spec:
  schedule: '3 */1 * * *'
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: fo-data
              nfs:
                path: /cephfs/fmipecan/openshift
                server: 193.166.192.225
                readOnly: false
          containers:
            - name: icos-downloader
              image: image-registry.openshift-image-registry.svc:5000/field-observatory/icos-downloader/icos-downloader:latest
              command: ["Rscript", "download_and_process.R", ">>", "/data/field-observatory/logs/icos-downloader.log"]
              volumeMounts:
                - name: fo-data
                  mountPath: /data
          restartPolicy: Never
