---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: fieldobs-satobs-cronjob
  namespace: field-observatory
spec:
  schedule: '0 6 * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: fo-data
              nfs:
                path: /cephfs/fmipecan/openshift
                server: 193.166.192.225
                readOnly: false
          containers:
            - name: filedobs-satobs
              image: image-registry.openshift-image-registry.svc:5000/field-observatory/fieldobs-satobs:latest
              resources:
                limits:
                  memory: 512Mi
                requests:
                  memory: 128Mi
              command: ["/bin/bash", "-c"]
              args: ["python -m fieldobs_satobs /data/field-observatory/field-observatory.yml 2>&1 | tee -a /data/field-observatory/logs/fieldobs-satobs-cronjob.log"]
              volumeMounts:
                - name: fo-data
                  mountPath: /data
          restartPolicy: Never
