---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-ui-geojsons-cronjob
  namespace: field-observatory
spec:
  schedule: '0 1 * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: fo-data
              nfs:
                path: /cephfs/fmipecan/openshift
                server: 193.166.192.225
                readOnly: false
          containers:
            - name: update-ui-geojsons
              image: image-registry.openshift-image-registry.svc:5000/field-observatory/update-ui-geojsons:latest
              command: ["/bin/bash", "-c"]
              args: [""python3 -u -m /app/fieldobs_utils/fieldobs_utils.bucket update_metadata field-observatory.yml --update_ui_geojsons 2>&1 | tee -a /data/field-observatory/logs/update-ui-geojsons-cronjob.log"]
              volumeMounts:
                - name: fo-data
                  mountPath: /data
          restartPolicy: Never
