---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: fieldobs-ecsites-run-gapfilling-cronjob
  namespace: field-observatory
spec:
  schedule: '30 7 * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: fo-data
              nfs:
                path: /cephfs/fmipecan/openshift
                server: 193.166.192.225
                readOnly: false
          containers:
            - name: filedobs-ecsites-update-smearflux
              image: image-registry.openshift-image-registry.svc:5000/field-observatory/fieldobs-ecsites:latest
              command: ["/bin/bash", "-c"]
              args: ["python -m fieldobs_ecsites.ecsites run_gapfilling /data/field-observatory/field-observatory.yml 2>&1 | tee -a /data/field-observatory/logs/fieldobs-ecsites-run-gapfilling-cronjob.log"]
              resources:
                limits:
                  cpu: 1000m
                  memory: 2000mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              volumeMounts:
                - name: fo-data
                  mountPath: /data
          restartPolicy: Never
