---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: fmi-meteo-downloader-cronjob
  namespace: field-observatory
spec:
  schedule: '1 */1 * * *'
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: fo-data
              nfs:
                path: /cephfs/fmipecan/openshift
                server: 193.166.192.225
                readOnly: false
          containers:
            - name: fmi-meteo-downloader
              image: image-registry.openshift-image-registry.svc:5000/field-observatory/fmi-meteo-downloader:latest
              command: ["/bin/bash", "-c"]
              args: ["python3 -u /project/src/main.py 2>&1 | tee -a /data/field-observatory/logs/fmi-meteo-downloader-cronjob.log"]
              volumeMounts:
                - name: fo-data
                  mountPath: /data
          restartPolicy: Never
