---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: hy-rclone-cronjob
  namespace: field-observatory
spec:
  timeZone: "Europe/Helsinki"
  schedule: '15 6 * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: fo-data
              nfs:
                path: /cephfs/fmipecan/openshift
                server: 193.166.192.225
                readOnly: false
            - name: rclone-conf
              configMap:
                name: rclone-conf
          containers:
            - name: hy-rclone
              image: image-registry.openshift-image-registry.svc:5000/field-observatory/hy-rclone:latest
              resources:
                limits:
                  memory: 512Mi
                requests:
                  memory: 128Mi
              command: ["/bin/sh", "-c"]
              args: ['rclone sync --config /conf/rclone.conf --ignore-times --verbose uh_datacloud: /data/hy-eddy2/data/ --exclude "{rottas,Rottas}*"  2>&1 | tee -a /data/field-observatory/logs/hy-rclone-cronjob.log']
              volumeMounts:
                - name: fo-data
                  mountPath: /data
                - name: rclone-conf
                  mountPath: /conf/rclone.conf
                  subPath: rclone.conf
          restartPolicy: Never
